### ISSUE TITLE
You forgot to add requirements.txt

### ISSUE THREAD

**Issue by deshwalmahesh** [ankit8697/BibTexConverter#1]
You have `*.txt` in `gitignore`. 

Also, after `pip install bibtexparser` manually, it gives: 
```
starting conversion...
Traceback (most recent call last):
  File "/content/BibTexConverter/BibTexConverter/./jstor.py", line 10, in <module>
    library = bibtexparser.parse_file(f"{FILE_NAME}.txt")
AttributeError: module 'bibtexparser' has no attribute 'parse_file'
```
Which means wither it's a different package or a different version.

So maybe, instead of "DIY"  `Readme` you could add a bug free code.

PS: Run a `streamlit` app instead of `Flask`.  It provides free Cloud space and entrypoint for Anyone to use it for free.

**Comment by ankit8697** [comment]
Yeah I forgot to exclude the requirements.txt from the gitignore. The code works, you'll just need the correct version (which is in the now added requirements.txt). Feel free to send a pull request that runs this on streamlit!
